name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # run daily
  workflow_dispatch:       # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pacman graph
        uses: Platane/snk@v3
        with:
          github_user_name: Nitinpratap22061
          outputs: |
            ./output/pacman-contribution-graph.svg?palette=github-dark&color_snake=yellow&mode=Pac-Man
            ./output/pacman-contribution-graph-dark.svg?palette=github-dark&color_snake=yellow&mode=Pac-Man

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "update pacman contribution graph" || echo "No changes to commit"
          git push
