name: generate-pacman-contribution-graph

on:
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight UTC
  workflow_dispatch:       # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Clone activity graph generator
        run: git clone https://github.com/Ashutosh00710/github-readme-activity-graph.git generator

      - name: Install dependencies
        run: cd generator && npm install

      - name: Generate Pacman Graph
        run: |
          cd generator
          node ./index.js --username Nitinpratap22061 --theme pacman --hide_border true --output ../output/pacman-contribution-graph.svg

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "update pacman contribution graph" || echo "No changes to commit"
          git push
